#!/usr/bin/env lua
-- generate.lua - Generate xmake.lua files for individual projects
-- This script generates xmake.lua files for projects that don't have native
-- cmake/autoconf support (e.g., serf which uses SCons).

local rootdir = arg[0]:match("(.*/)") or "./"
local installdir = path.join(rootdir, "build", "install")

-- Generate serf xmake.lua
local function generate_serf()
    local content = [[
-- Auto-generated xmake.lua for serf
-- This file is generated by generate.lua, do not edit manually

set_xmakever("2.8.0")
add_rules("mode.debug", "mode.release")

target("serf")
    set_kind("shared")

    -- Source files
    add_files("*.c")
    add_files("buckets/*.c")
    add_files("auth/*.c")

    -- Include paths
    add_includedirs(".")
    add_includedirs("]] .. path.join(installdir, "include", "apr-1") .. [[")
    add_includedirs("]] .. path.join(installdir, "include") .. [[")

    -- Defines
    add_defines("SERF_SHARED")
    add_defines("OPENSSL_NO_STDIO")

    -- Dependencies
    add_links("ssl", "crypto", "z", "apr-1", "aprutil-1")
    add_linkdirs("]] .. path.join(installdir, "lib") .. [[")

    -- Install
    set_targetdir("]] .. path.join(installdir, "lib") .. [[")
    set_basename("serf-1")

    after_install(function (target)
        os.cp("serf.h", "]] .. path.join(installdir, "include", "serf-1") .. [[/")
        os.cp("serf_bucket_types.h", "]] .. path.join(installdir, "include", "serf-1") .. [[/")
        os.cp("serf_bucket_util.h", "]] .. path.join(installdir, "include", "serf-1") .. [[/")
    end)
target_end()
]]
    local f = io.open(path.join(rootdir, "serf", "xmake.lua"), "w")
    if f then
        f:write(content)
        f:close()
        print("Generated serf/xmake.lua")
    else
        print("Error: Could not write serf/xmake.lua")
    end
end

-- Main
if arg[1] == "serf" or arg[1] == nil then
    generate_serf()
end

print("Done!")
