-- generate.lua - Generate xmake.lua files for sub-projects
-- Usage: xmake lua generate.lua

local rootdir = os.scriptdir()

-- ============================================================
-- Generate serf xmake.lua
-- ============================================================
local function generate_serf()
    local content = string.format([[
-- Auto-generated xmake.lua for serf
-- Generated by: xmake lua generate.lua

add_rules("mode.debug", "mode.release")

target("serf-1")
    set_kind("shared")

    -- Source files
    add_files("context.c", "incoming.c", "outgoing.c", "ssltunnel.c")
    add_files("buckets/*.c")
    add_files("auth/*.c")

    -- Include paths (dependencies must be installed first)
    add_includedirs(".")
    if os.isdir("../build/install/include/apr-1") then
        add_includedirs("../build/install/include/apr-1")
    end
    if os.isdir("../build/install/include") then
        add_includedirs("../build/install/include")
    end

    -- Defines
    add_defines("SERF_SHARED", "OPENSSL_NO_STDIO")

    -- Link dependencies
    if os.isdir("../build/install/lib") then
        add_linkdirs("../build/install/lib")
    end
    add_links("ssl", "crypto", "z", "apr-1", "aprutil-1")

    -- Platform specific
    if is_plat("linux") then
        add_syslinks("pthread")
    end

    -- Output
    set_targetdir("lib")
    add_headerfiles("serf.h", "serf_bucket_types.h", "serf_bucket_util.h")
target_end()
]])

    local outfile = path.join(rootdir, "serf", "xmake.lua")
    io.writefile(outfile, content)
    print("Generated: " .. outfile)
end

-- ============================================================
-- Main
-- ============================================================
print("Generating xmake.lua files...")
generate_serf()
print("Done!")
