-- generate.lua - Generate xmake.lua files for sub-projects
-- Usage: xmake lua generate.lua

local rootdir = os.scriptdir()

-- ============================================================
-- Find package install directory
-- ============================================================
local function find_package_dir(name)
    local pkg_cache = path.join(rootdir, "build", ".packages")
    local first_char = name:sub(1, 1)
    local pkg_path = path.join(pkg_cache, first_char, name, "latest")
    if os.isdir(pkg_path) then
        for _, hash_dir in ipairs(os.dirs(path.join(pkg_path, "*"))) do
            if path.filename(hash_dir) ~= "cache" and os.isdir(path.join(hash_dir, "lib")) then
                return hash_dir
            end
        end
    end
    return nil
end

-- ============================================================
-- Generate serf xmake.lua
-- ============================================================
local function generate_serf()
    -- Find dependency paths
    local apr_dir = find_package_dir("apr")
    local aprutil_dir = find_package_dir("apr-util")
    local openssl_dir = find_package_dir("openssl")
    local zlib_dir = find_package_dir("zlib")

    if not apr_dir or not aprutil_dir or not openssl_dir or not zlib_dir then
        print("Error: Dependencies not found. Please run first:")
        print("  xmake require -y zlib libexpat openssl sqlite apr apr-util")
        os.exit(1)
    end

    -- Generate absolute paths
    local apr_inc = path.join(apr_dir, "include", "apr-1")
    local aprutil_inc = path.join(aprutil_dir, "include", "apr-1")
    local openssl_inc = path.join(openssl_dir, "include")
    local zlib_inc = path.join(zlib_dir, "include")
    local apr_lib = path.join(apr_dir, "lib")
    local aprutil_lib = path.join(aprutil_dir, "lib")
    local openssl_lib = path.join(openssl_dir, "lib")
    local zlib_lib = path.join(zlib_dir, "lib")
    local installdir = path.join(rootdir, "build", "install")

    local content = string.format([[
-- Auto-generated xmake.lua for serf
-- Generated by: xmake lua generate.lua

target("serf")
    set_kind("shared")
    set_basename("serf-1")

    -- Source files
    add_files("serf/context.c", "serf/incoming.c", "serf/outgoing.c", "serf/ssltunnel.c")
    add_files("serf/buckets/*.c")
    add_files("serf/auth/*.c")

    -- Include paths (from package cache)
    add_includedirs("serf")
    add_includedirs("%s")
    add_includedirs("%s")
    add_includedirs("%s")
    add_includedirs("%s")

    -- Defines
    add_defines("SERF_SHARED", "OPENSSL_NO_STDIO")

    -- Link dependencies
    add_links("ssl", "crypto", "z", "apr-1", "aprutil-1")
    add_linkdirs("%s", "%s", "%s", "%s")

    -- Platform specific
    if is_plat("linux") then
        add_syslinks("pthread")
    end

    -- Output to install directory
    set_targetdir("%s/lib")

    -- After build, copy headers to install directory
    after_build(function (target)
        local incdir = path.join("%s", "include", "serf-1")
        os.mkdir(incdir)
        os.cp(path.join(os.scriptdir(), "serf", "serf.h"), incdir)
        os.cp(path.join(os.scriptdir(), "serf", "serf_bucket_types.h"), incdir)
        os.cp(path.join(os.scriptdir(), "serf", "serf_bucket_util.h"), incdir)
        print("Serf headers installed to: " .. incdir)
    end)
target_end()
]], apr_inc, aprutil_inc, openssl_inc, zlib_inc,
    apr_lib, aprutil_lib, openssl_lib, zlib_lib,
    installdir, installdir)

    local outfile = path.join(rootdir, "serf_build.lua")
    io.writefile(outfile, content)
    print("Generated: " .. outfile)
    print("")
    print("Dependency paths:")
    print("  APR: " .. (apr_dir or "NOT FOUND"))
    print("  APR-Util: " .. (aprutil_dir or "NOT FOUND"))
    print("  OpenSSL: " .. (openssl_dir or "NOT FOUND"))
    print("  zlib: " .. (zlib_dir or "NOT FOUND"))
end

-- ============================================================
-- Main
-- ============================================================
print("Generating xmake.lua files for sub-projects...")
generate_serf()
print("")
print("Done! You can now build with:")
print("  xmake build -y svn-build")
